import type { ProductAdmin, Promotion, RestockOrder, Order } from "./types"

// Stub products for admin CRUD
export const ADMIN_PRODUCTS: ProductAdmin[] = [
  {
    ProductID: "prod-001",
    name: "Salmon Onigiri",
    priceSGD: 2.5,
    stock: 45,
    brand: "FamilyMart",
    category: "Onigiri & Rice Balls",
    expiryDate: "2025-01-15",
    img: "/salmon-onigiri-rice-ball.jpg",
  },
  {
    ProductID: "prod-002",
    name: "Tuna Mayo Onigiri",
    priceSGD: 2.3,
    stock: 8,
    brand: "FamilyMart",
    category: "Onigiri & Rice Balls",
    expiryDate: "2025-01-14",
    img: "/tuna-mayo-onigiri.jpg",
  },
  {
    ProductID: "prod-003",
    name: "Chicken Teriyaki Bento",
    priceSGD: 6.9,
    stock: 12,
    brand: "FamilyMart",
    category: "Bento & Hot Meals",
    expiryDate: "2025-01-10",
    discountRate: 0.3,
    img: "/chicken-teriyaki-bento.jpg",
  },
  {
    ProductID: "prod-004",
    name: "Egg Sandwich",
    priceSGD: 3.5,
    stock: 25,
    brand: "FamilyMart",
    category: "Sandwiches & Bakery",
    expiryDate: "2025-01-12",
    img: "/egg-sandwich.jpg",
  },
  {
    ProductID: "prod-005",
    name: "Fried Chicken",
    priceSGD: 4.2,
    stock: 5,
    brand: "FamilyMart",
    category: "Hot Snacks",
    img: "/fried-chicken.jpg",
  },
  {
    ProductID: "prod-006",
    name: "Cup Noodles Curry",
    priceSGD: 2.8,
    stock: 50,
    brand: "Nissin",
    category: "Instant Noodles",
    img: "/cup-noodles.jpg",
  },
  {
    ProductID: "prod-007",
    name: "Caesar Salad",
    priceSGD: 5.5,
    stock: 15,
    brand: "FamilyMart",
    category: "Salads & Sides",
    expiryDate: "2025-01-11",
    img: "/caesar-salad.jpg",
  },
  {
    ProductID: "prod-008",
    name: "Matcha Ice Cream",
    priceSGD: 3.9,
    stock: 30,
    brand: "Meiji",
    category: "Desserts & Ice Cream",
    img: "/matcha-ice-cream.jpg",
  },
  {
    ProductID: "prod-009",
    name: "Green Tea",
    priceSGD: 1.8,
    stock: 3,
    brand: "Pokka",
    category: "Beverages",
    img: "/green-tea.jpg",
  },
  {
    ProductID: "prod-010",
    name: "Frozen Pizza",
    priceSGD: 7.5,
    stock: 20,
    brand: "Dr. Oetker",
    category: "Frozen",
    img: "/frozen-pizza.jpg",
  },
  {
    ProductID: "prod-011",
    name: "Tissue Box",
    priceSGD: 2.2,
    stock: 40,
    brand: "Kleenex",
    category: "Daily Necessities",
  },
  {
    ProductID: "prod-012",
    name: "Umeboshi Onigiri",
    priceSGD: 2.4,
    stock: 6,
    brand: "FamilyMart",
    category: "Onigiri & Rice Balls",
    expiryDate: "2025-01-09",
    discountRate: 0.5,
    img: "/umeboshi-onigiri-plum.jpg",
  },
]

// Stub promotions
export const STUB_PROMOTIONS: Promotion[] = [
  {
    promoId: "promo-001",
    name: "New Year Sale",
    discountRate: 0.2,
    startDate: "2025-01-01",
    endDate: "2025-01-31",
  },
  {
    promoId: "promo-002",
    name: "Hot Snacks Special",
    discountRate: 0.15,
    startDate: "2025-01-05",
    endDate: "2025-01-20",
  },
  {
    promoId: "promo-003",
    name: "Dessert Week",
    discountRate: 0.25,
    startDate: "2025-01-08",
    endDate: "2025-01-15",
  },
]

// Stub restock orders
export const STUB_RESTOCK_ORDERS: RestockOrder[] = [
  {
    id: "restock-001",
    supplier: "FamilyMart Warehouse",
    items: [
      { productId: "prod-002", qty: 50, productName: "Tuna Mayo Onigiri" },
      { productId: "prod-005", qty: 30, productName: "Fried Chicken" },
    ],
    status: "sent",
    createdAt: "2025-01-05T10:00:00Z",
    expectedDate: "2025-01-08",
  },
  {
    id: "restock-002",
    supplier: "Pokka Distributors",
    items: [{ productId: "prod-009", qty: 100, productName: "Green Tea" }],
    status: "draft",
    createdAt: "2025-01-06T14:30:00Z",
    expectedDate: "2025-01-10",
  },
]

// Stub orders for order history
export const STUB_ORDERS: Order[] = [
  {
    id: "order-001",
    number: "1001",
    origin: "kiosk",
    items: [
      {
        lineId: "line-001",
        productId: "prod-001",
        name: "Salmon Onigiri",
        qty: 2,
        unitPrice: 2.5,
        lineTotal: 5.0,
      },
      {
        lineId: "line-002",
        productId: "prod-009",
        name: "Green Tea",
        qty: 1,
        unitPrice: 1.8,
        lineTotal: 1.8,
      },
    ],
    totals: {
      subtotal: 6.8,
      discounts: 0,
      total: 6.8,
    },
    status: "completed",
    createdAt: "2025-01-06T09:15:00Z",
    qrToken: "qr-001",
  },
  {
    id: "order-002",
    number: "1002",
    origin: "kiosk",
    items: [
      {
        lineId: "line-003",
        productId: "prod-003",
        name: "Chicken Teriyaki Bento",
        qty: 1,
        unitPrice: 4.83,
        lineTotal: 4.83,
      },
    ],
    totals: {
      subtotal: 6.9,
      discounts: 2.07,
      total: 4.83,
    },
    status: "pending",
    createdAt: "2025-01-06T10:30:00Z",
    qrToken: "qr-002",
  },
  {
    id: "order-003",
    number: "1003",
    origin: "kiosk",
    items: [
      {
        lineId: "line-004",
        productId: "prod-005",
        name: "Fried Chicken",
        qty: 3,
        unitPrice: 4.2,
        lineTotal: 12.6,
      },
    ],
    totals: {
      subtotal: 12.6,
      discounts: 0,
      total: 12.6,
    },
    status: "completed",
    createdAt: "2025-01-06T11:00:00Z",
    qrToken: "qr-003",
  },
]
